// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lirmi.Challenge.Data.Entities
{
    public partial class Grade
    {
        public Grade()
        {
            Subject = new HashSet<Subject>();
        }

        public int GradeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int YearNumber { get; set; }
        public string Type { get; set; }
        public int SchoolId { get; set; }
        public bool? IsActive { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? CreatedUserId { get; set; }
        public DateTime UpdatedDate { get; set; }
        public int? UpdatedUserId { get; set; }

        public virtual School School { get; set; }
        public virtual ICollection<Subject> Subject { get; set; }
    }
}